version: '3.7'

services:
  app:
    build:
      context: .
      target: dev
    image: memento-dev
    ports:
      - '5000:5000'
    depends_on: 
      - postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      FLASK_APP: app/server.py

  postgres:
    image: postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    env_file:
      - .env

volumes:
  pgdata: null