version: '3.8'

services:
  app:
    build:
      context: .
    image: anki-dev
    volumes:
      - '.:/srv/app'
    ports:
      - '5000:5000'
    depends_on: 
      - postgres
    restart: unless-stopped
    environment:
      ## Путь к точке создания приложения
      FLASK_APP: app/run.py
      ## Секретный ключ - а для чего?
      SECRET_KEY: '!! Something secret !!'
      ## TOKEN для дева пусть у каждого свой будет
      ## Данные для доступа к постгресу (да, они отдельно, а не одним урлом)
      DATABASE_USER: dev
      DATABASE_PASS: devpass
      DATABASE_HOST: postgres
      DATABASE_NAME: ankibot
      BOT_SECRET_PATH: secret
  postgres:
    image: postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: ankibot

volumes:
  pgdata: null