version: 1

formatters:
  default:
    format: '%(asctime)s %(levelname)s in %(module)s.%(funcName)s [%(lineno)d]: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/memento.log
    maxBytes: 1024
    backupCount: 3

loggers:
  app:
    level: DEBUG
    handlers: [console, file]

root:
  level: DEBUG
  handlers: [console, file]
